#ifndef _AWE_VERSION_INTERNAL_H_
#define _AWE_VERSION_INTERNAL_H_

#define AWESOME_VERSION             "AWESOMEVERSION"
#define AWESOME_COMPILE_MACHINE     "AWESOMEARCH"
#define AWESOME_RELEASE             "AWESOMEREL"

#endif //_AWE_VERSION_INTERNAL_H_
